import * as path from 'path'
import { writeFile, mkdir } from 'fs/promises'
import * as https from 'https'

// Pin to a tagged GitHub release of trilitech/octez.connect-wallet-list, so
// the data the SDK ships with is stable and reproducible across builds. Bump
// WALLET_LIST_VERSION to consume a new release; override via the
// WALLET_LIST_VERSION env var for ad-hoc upgrades.
const WALLET_LIST_VERSION = process.env.WALLET_LIST_VERSION ?? 'v1.0.3'
const GITHUB_RELEASE_BASE = `https://github.com/trilitech/octez.connect-wallet-list/releases/download/${WALLET_LIST_VERSION}`
const BEACON_UI_DATA_DIR = path.join(process.cwd(), 'packages/octez.connect-ui/src/data')

// Bundled fallbacks for the blockchain packages are generated as TS modules,
// NOT .json imports: those packages compile with plain tsc, so a .json import
// survives into their published dist as a cross-package subpath
// (@tezos-x/octez.connect-ui/data/*.json) that CDNs like esm.sh cannot serve
// as a per-file module (404 on data/tezos.json.mjs → the whole SDK import
// fails). A TS module compiles the data into each package's own dist.
const TS_FALLBACK_TARGETS: Record<string, string> = {
  'tezos.json': 'packages/octez.connect-blockchain-tezos/src/data/bundled-wallet-registry.ts',
  'substrate.json': 'packages/octez.connect-blockchain-substrate/src/data/bundled-wallet-registry.ts',
  'tezos-sapling.json':
    'packages/octez.connect-blockchain-tezos-sapling/src/data/bundled-wallet-registry.ts'
}

function tsFallbackModule(jsonContent: string): string {
  const registry = JSON.stringify(JSON.parse(jsonContent), null, 2)
  return [
    '// Generated by scripts/download-wallet-lists.ts from',
    `// trilitech/octez.connect-wallet-list ${WALLET_LIST_VERSION} — do not edit by hand.`,
    '// Offline fallback for the CDN fetch in getWalletLists().',
    `export const bundledWalletRegistry = ${registry}`,
    ''
  ].join('\n')
}

async function downloadFile(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https.get(url, (response) => {
      if (response.statusCode === 301 || response.statusCode === 302) {
        if (response.headers.location) {
          return downloadFile(response.headers.location).then(resolve).catch(reject)
        }
      }
      if (response.statusCode !== 200) {
        return reject(new Error(`HTTP ${response.statusCode}`))
      }
      let data = ''
      response.on('data', (chunk) => (data += chunk))
      response.on('end', () => resolve(data))
    }).on('error', reject)
  })
}

async function download() {
  try {
    await mkdir(BEACON_UI_DATA_DIR, { recursive: true })

    const files = ['tezos.json', 'substrate.json', 'tezos-sapling.json']

    for (const file of files) {
      console.log(`Downloading ${file}...`)
      const content = await downloadFile(`${GITHUB_RELEASE_BASE}/${file}`)
      await writeFile(path.join(BEACON_UI_DATA_DIR, file), content)

      const tsTarget = TS_FALLBACK_TARGETS[file]
      if (tsTarget) {
        const tsPath = path.join(process.cwd(), tsTarget)
        await mkdir(path.dirname(tsPath), { recursive: true })
        await writeFile(tsPath, tsFallbackModule(content))
      }
    }

    console.log(`All wallet lists downloaded successfully (release ${WALLET_LIST_VERSION})`)
  } catch (error) {
    console.error('Download failed:', error)
    process.exit(1)
  }
}

download()
