name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - 4.8.2

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  build-docs:
    name: build-docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build API docs
        run: npm run typedoc

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-docs:
    name: deploy-docs
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
